# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glue/qt/ui/imagewidget.ui'
#
# Created: Wed Jul 31 15:07:25 2013
#      by: pyside-uic 0.2.13 running on glue.external.qt 1.1.0
#
# WARNING! All changes made in this file will be lost!

from glue.external.qt import QtCore, QtGui

class Ui_ImageWidget(object):
    def setupUi(self, ImageWidget):
        ImageWidget.setObjectName("ImageWidget")
        ImageWidget.resize(296, 217)
        ImageWidget.setBaseSize(QtCore.QSize(555, 500))
        ImageWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ImageWidget)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.option_dashboard = QtGui.QWidget(ImageWidget)
        self.option_dashboard.setObjectName("option_dashboard")
        self.verticalLayout = QtGui.QVBoxLayout(self.option_dashboard)
        self.verticalLayout.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.option_dashboard)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.displayDataCombo = GlueComboBox(self.option_dashboard)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayDataCombo.sizePolicy().hasHeightForWidth())
        self.displayDataCombo.setSizePolicy(sizePolicy)
        self.displayDataCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.displayDataCombo.setObjectName("displayDataCombo")
        self.horizontalLayout.addWidget(self.displayDataCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.option_dashboard)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.attributeComboBox = GlueComboBox(self.option_dashboard)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributeComboBox.sizePolicy().hasHeightForWidth())
        self.attributeComboBox.setSizePolicy(sizePolicy)
        self.attributeComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.attributeComboBox.setObjectName("attributeComboBox")
        self.horizontalLayout_2.addWidget(self.attributeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orientationLabel = QtGui.QLabel(self.option_dashboard)
        self.orientationLabel.setEnabled(True)
        self.orientationLabel.setObjectName("orientationLabel")
        self.horizontalLayout_3.addWidget(self.orientationLabel)
        self.sliceComboBox = GlueComboBox(self.option_dashboard)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceComboBox.sizePolicy().hasHeightForWidth())
        self.sliceComboBox.setSizePolicy(sizePolicy)
        self.sliceComboBox.setObjectName("sliceComboBox")
        self.horizontalLayout_3.addWidget(self.sliceComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.imageSlider = QtGui.QSlider(self.option_dashboard)
        self.imageSlider.setEnabled(True)
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setInvertedAppearance(False)
        self.imageSlider.setInvertedControls(True)
        self.imageSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.imageSlider.setTickInterval(0)
        self.imageSlider.setObjectName("imageSlider")
        self.verticalLayout.addWidget(self.imageSlider)
        spacerItem = QtGui.QSpacerItem(5, 59, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.option_dashboard)
        self.verticalLayout_2.setStretch(0, 1)

        self.retranslateUi(ImageWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageWidget)

    def retranslateUi(self, ImageWidget):
        ImageWidget.setWindowTitle(QtGui.QApplication.translate("ImageWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImageWidget", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataCombo.setToolTip(QtGui.QApplication.translate("ImageWidget", "Set which data set to display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ImageWidget", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.attributeComboBox.setToolTip(QtGui.QApplication.translate("ImageWidget", "Set which attribute of the data to display", None, QtGui.QApplication.UnicodeUTF8))
        self.orientationLabel.setText(QtGui.QApplication.translate("ImageWidget", "Slice Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.sliceComboBox.setToolTip(QtGui.QApplication.translate("ImageWidget", "Set how to slice 3D cubes", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSlider.setToolTip(QtGui.QApplication.translate("ImageWidget", "Adjust the position of the slice plane", None, QtGui.QApplication.UnicodeUTF8))

from ..qtutil import GlueComboBox
