# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glue/qt/ui/link_equation.ui'
#
# Created: Wed Jul 31 15:07:25 2013
#      by: pyside-uic 0.2.13 running on glue.external.qt 1.1.0
#
# WARNING! All changes made in this file will be lost!

from glue.external.qt import QtCore, QtGui

class Ui_LinkEquation(object):
    def setupUi(self, LinkEquation):
        LinkEquation.setObjectName("LinkEquation")
        LinkEquation.resize(466, 605)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(LinkEquation)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_label = QtGui.QLabel(LinkEquation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.top_label.setFont(font)
        self.top_label.setScaledContents(False)
        self.top_label.setAlignment(QtCore.Qt.AlignCenter)
        self.top_label.setObjectName("top_label")
        self.verticalLayout.addWidget(self.top_label)
        self.function = QtGui.QComboBox(LinkEquation)
        self.function.setObjectName("function")
        self.verticalLayout.addWidget(self.function)
        self.info = QtGui.QLabel(LinkEquation)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.info.setFont(font)
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        self.help_txt = QtGui.QLabel(LinkEquation)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setItalic(True)
        self.help_txt.setFont(font)
        self.help_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.help_txt.setMargin(0)
        self.help_txt.setObjectName("help_txt")
        self.verticalLayout.addWidget(self.help_txt)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_label = QtGui.QLabel(LinkEquation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.input_label.setFont(font)
        self.input_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.input_label.setObjectName("input_label")
        self.horizontalLayout.addWidget(self.input_label)
        self.input_canvas = QtGui.QWidget(LinkEquation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_canvas.sizePolicy().hasHeightForWidth())
        self.input_canvas.setSizePolicy(sizePolicy)
        self.input_canvas.setMinimumSize(QtCore.QSize(0, 0))
        self.input_canvas.setObjectName("input_canvas")
        self.horizontalLayout.addWidget(self.input_canvas)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.output_label = QtGui.QLabel(LinkEquation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.output_label.setFont(font)
        self.output_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output_label.setObjectName("output_label")
        self.horizontalLayout_2.addWidget(self.output_label)
        self.output_canvas = QtGui.QWidget(LinkEquation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_canvas.sizePolicy().hasHeightForWidth())
        self.output_canvas.setSizePolicy(sizePolicy)
        self.output_canvas.setMinimumSize(QtCore.QSize(0, 0))
        self.output_canvas.setObjectName("output_canvas")
        self.horizontalLayout_2.addWidget(self.output_canvas)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.addButton = QtGui.QPushButton(LinkEquation)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(4, 8)
        self.verticalLayout.setStretch(5, 8)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(LinkEquation)
        QtCore.QMetaObject.connectSlotsByName(LinkEquation)

    def retranslateUi(self, LinkEquation):
        LinkEquation.setWindowTitle(QtGui.QApplication.translate("LinkEquation", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.top_label.setText(QtGui.QApplication.translate("LinkEquation", "Select a function", None, QtGui.QApplication.UnicodeUTF8))
        self.function.setToolTip(QtGui.QApplication.translate("LinkEquation", "Select a translation function to use", None, QtGui.QApplication.UnicodeUTF8))
        self.info.setText(QtGui.QApplication.translate("LinkEquation", "result = f(x, y)", None, QtGui.QApplication.UnicodeUTF8))
        self.help_txt.setText(QtGui.QApplication.translate("LinkEquation", "Drag Component Identifiers from above", None, QtGui.QApplication.UnicodeUTF8))
        self.input_label.setText(QtGui.QApplication.translate("LinkEquation", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.output_label.setText(QtGui.QApplication.translate("LinkEquation", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setToolTip(QtGui.QApplication.translate("LinkEquation", "Create a new link defined by this translation description", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("LinkEquation", "Glue", None, QtGui.QApplication.UnicodeUTF8))

